config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :pay_programs
  end

  root 'overview#index'

  get 'overview' => 'overview#index', as: :overview

  put 'update_title' =>  'media_assets#update_title'

  resources :media_assets, path: 'library' do
    collection do
      get 'library'
      delete 'destroy_multiple'
    end
  end

  resources :template_addons

  resources :loop_assets do
    resources :slide_assets, except: [:index, :destroy] do
      member do
        get 'htmlsrc'
        get 'preview'
      end
    end
    member do
      get 'getdata'
    end
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :campaigns do
    member do
      get 'getdata'
      get 'exception_form'
    end
  end

  resources :players, except: [:new, :create, :destroy] do
    member do
      post 'getdata'
      get 'getfiles'
      post 'sendCommand'
    end
  end

  resources :users

  resources :organizations, only: [:show, :edit, :update]

  get 'signup'  => 'users#new'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: :logout

  namespace :admin do
    root to: 'overview#index'
    resources :organizations, only: [:index, :show, :edit, :update, :new, :create, :destroy] do
      collection do
        post 'becomeOrg'
      end
    end
    resources :users, only: [:index, :edit, :update, :show, :new, :create, :destroy]
    resources :hardware_types
    resources :players do
      member do
        post 'resetconnection'
      end
    end
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :organization
  belongs_to :loop_asset
  belongs_to :campaign
  belongs_to :admin_hardware_type, :class_name => "Admin::HardwareType"
  belongs_to :admin_pay_program, :class_name => "Admin::PayProgram"
  serialize :diagnostics, Hash

  validates :name, length: { maximum: 50 }
  validates :description, length: { maximum: 500 }
  validates :admin_hardware_type, presence: true
  validates :serial_number, presence: true
  validates :admin_pay_program, presence: true

  before_save :bubble_update, if: "self.campaign_id_changed?"

  def bubble_update 
    self.touch(:last_update_stamp)
  end

  private

    # Cusom Validations
    # Ensure the loop asset belongs to the organization
    def loop_asset_accessible
      if loop_asset.organization != self.organization
        errors.add(:loop_asset, "is not accessable")
      end
    end
end

app/controllers/admin/players_controller.rb
# ADMIN 
class Admin::PlayersController < ApplicationController
  include FlashMessages
  include AuthenticateUser

  before_action :logged_in_user, except: [:getdata, :getfiles]
  before_action :soadmin_user

  before_action :set_player, only: [:show, :edit, :update, :destroy, :resetconnection]

  # GET /players
  def index
    allplayers = Player.all
    @players = allplayers.where(activated: true)
    @pendingplayers = allplayers.where(activated: false);
  end

  # GET /players/1
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
    @player.organization_id = params[:orgid]
    @player.name = "New Player"
    @player.description = "No description set"
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  def create
    @player = Player.new(new_player_params)
    @player.activated = false
    @player.access_code = SecureRandom.hex(4)

    if @player.save
      redirect_to [:admin, @player], notice: 'Player was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /players/1
  def update
    if @player.update(edit_player_params)
      redirect_to admin_players_url, notice: 'Player was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /players/1
  def destroy
    @player.destroy
    redirect_to admin_players_url, notice: 'Player was successfully destroyed.'
  end

  # POST /players/1/resetconnection
  def resetconnection
    @player.activated = false
    @player.uniqkey = nil
    if @player.save
      redirect_to [:admin, @player], notice: 'Secret access key reset. Please reconnect player to complete.'
    else
      redirect_to [:admin, @player], alert: "Couldn't reset the connection code."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def new_player_params
      params.require(:player).permit(:name, :description, :serial_number, :organization_id, :admin_pay_program_id, :admin_hardware_type_id)
    end
    def edit_player_params
      params.require(:player).permit(:name, :description)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  include FlashMessages
  include AuthenticateUser
  include LogMessages

  before_action :logged_in_user, except: [:getdata, :getfiles]
  before_action :allowed_player, only: [:getdata, :getfiles]

  before_action :set_player, only: [:show, :edit, :update, :getdata, :getfiles, :sendCommand, :activate]
  before_action :check_player_ownership, only: [:show, :edit, :update, :activate, :sendCommand]
  before_action :check_player_ownership_api, only: [:getdata, :getfiles]

  skip_before_filter :verify_authenticity_token, :only => [:getdata]

  # GET /players
  def index
    allplayers = current_user.organization.players
    @players = allplayers.where(activated: true)
    @pendingplayers = allplayers.where(activated: false);
  end

  # GET /players/1
  def show
  end

  # GET /players/1/edit
  def edit
  end

  # PATCH/PUT /players/1
  def update
    if @player.update(edit_player_params)
      log("edited player #{@player.name}", @player)
      redirect_to players_url, notice: 'Player was successfully updated.'
    else
      render :edit
    end
  end

  # This action reports information to the requesting player
  # GET /players/1/getdata.json
  def getdata
    if @player.activated == false
      if !@player.update_attribute(:activated, true) || !@player.update_attribute(:uniqkey, params[:uniqkey])
        render status: 500
        return
      end      
    end
    render :getdata, layout: false
    @player.diagnostics[:lastReboot] = params[:lastReboot]
    @player.diagnostics[:currentCampaign] = params[:currentCampaign]
    @player.diagnostics[:lastUpdateStamp] = params[:lastUpdateStamp]
    @player.pending_action = nil
    @player.save
    @player.touch(:last_connection)
  end

  # This action lists required files to the requesting player
  # GET /players/1/getfiles.json
  def getfiles
    render :getfiles, layout: false
  end

  # This action sends commands to the player
  # POST /players/1/sendCommand?command=restart
  def sendCommand
    if params[:command] == 'restart'
      @player.pending_action = 'reboot'
    elsif params[:command] == 'contentReload'
      @player.pending_action = 'forceReload'
    elsif params[:command] == 'clear'
      @player.pending_action = nil
    else
      redirect_to @player, notice: 'Unsupported command'
      return
    end
    
    if @player.save
      redirect_to @player, notice: 'Command pending'
    else
      redirect_to @player, notice: 'Error sending command'
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    def check_player_ownership
      redirect_to(root_url) unless current_user.organization == @player.organization
    end

    def check_player_ownership_api
      if params[:player_id] != @player.id.to_s
        render nothing: true, status: :unauthorized
        return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edit_player_params
      params.require(:player).permit(:name, :description, :campaign_id)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/admin/players/_edit_form.html.erb
<%= form_for([:admin, @player]) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :campaign %><br>
    <%= f.collection_select(:campaign_id, current_user.organization.campaigns, :id, :displayname, :prompt => 'Please select campaign', :include_blank => true) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/players/_new_form.html.erb
<h2>For Organization: <%= @player.organization.name %></h2>
<%= form_for([:admin, @player]) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :organization_id %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :serial_number, 'Serial Number' %><br>
    <%= f.text_field :serial_number %>
  </div>
  <div class="field">
    <%= f.label :admin_hardware_type, 'Hardware Type' %><br>
    <%= f.collection_select(:admin_hardware_type_id, Admin::HardwareType.all, :id, :model_number, :prompt => 'Please select Model') %>
  </div>
  <div class="field">
    <%= f.label :admin_pay_program, 'Payment Plan' %><br>
    <%= f.collection_select(:admin_pay_program_id, Admin::PayProgram.all, :id, :name, :prompt => 'Please select payment plan') %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/players/edit.html.erb
<%= render partial: 'admin/shared/admin_nav' %>
<h1>Editing player</h1>

<%= render 'edit_form' %>

<%= link_to 'Show', [:admin, @player] %> |
<%= link_to 'Back', admin_players_path %>

app/views/admin/players/index.html.erb
<%= render partial: 'admin/shared/admin_nav' %>
<h1>Listing players</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Organization</th>
      <th>Name</th>
      <th>Description</th>
      <th>Running Campaign</th>
      <th>Last Connection</th>
      <th>Diagnostics</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to player.organization.name, [:admin, player.organization] %></td>
        <td><%= link_to player.name, [:admin, player] %></td>
        <td><%= player.description %></td>
        <td><%= player.campaign.displayname if player.campaign %></td>
        <td><%= time_ago_in_words(player.last_connection)%> ago</td>
        <td><%= player.diagnostics %></td>
        <td><%= link_to 'Edit', edit_admin_player_path(player) %></td>
        <td><%= link_to 'Destroy', [:admin, player], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% if !@pendingplayers.empty?%>
  <h4>Pending Players</h4>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Organization</th>
        <th>Player Code</th>
        <th>Access Code</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @pendingplayers.each do |pplayer| %>
        <tr>
          <td><%= link_to pplayer.organization.name, [:admin, pplayer.organization] %></td>
          <td><%= pplayer.id %></td>
          <td><%= pplayer.access_code %></td>
          <td><%= link_to 'Destroy', [:admin, pplayer], method: :delete, data: { confirm: 'Are you sure you want to delete this player?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/admin/players/new.html.erb
<%= render partial: 'admin/shared/admin_nav' %>
<h1>New player</h1>

<%= render 'new_form' %>

<%= link_to 'Back', admin_players_path %>

app/views/admin/players/show.html.erb
<%= render partial: 'admin/shared/admin_nav' %>
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @player.description %>
</p>

<p>
  <strong>Hardware Type:</strong>
  <%= link_to @player.admin_hardware_type.model_number, @player.admin_hardware_type %>
</p>

<p>
  <strong>Serial Number:</strong>
  <%= @player.serial_number %>
</p>

<p>
  <strong>Payment Plan:</strong>
  <%= link_to @player.admin_pay_program.name, @player.admin_pay_program %>
</p>

<p>
  <strong>Campaign:</strong>
  <%= @player.campaign ? @player.campaign.displayname : 'None Selected' %>
</p>

<p>
	<strong>Player Registration Details</strong><br>
	Player Code: <%= @player.id %><br>
	Access Code: <%= @player.access_code %> 
</p>

<p>

	<% if (pa=@player.pending_action) %>
		<strong>Pending Action:</strong> 
		<%= pa %>
		<%= button_to 'Clear', sendCommand_player_path(@player), {:method => :post, :params => {command: 'clear'}} %>
		<br/>
	<% end %>
	<%= button_to 'Restart Player', sendCommand_player_path(@player), {:method => :post, :params => {command: 'restart'}} %>
	<%= button_to 'Force Content Reload', sendCommand_player_path(@player), {:method => :post, :params => {command: 'contentReload'}} %>
  <%= button_to 'Reset Connection', resetconnection_admin_player_path(@player) %>
</p>


<%= link_to 'Edit', edit_admin_player_path(@player) %> |
<%= link_to 'Back', admin_players_path %>