config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :pay_programs
  end

  root 'overview#index'

  get 'overview' => 'overview#index', as: :overview

  put 'update_title' =>  'media_assets#update_title'

  resources :media_assets, path: 'library' do
    collection do
      get 'library'
      delete 'destroy_multiple'
    end
  end

  resources :template_addons

  resources :loop_assets do
    resources :slide_assets, except: [:index, :destroy] do
      member do
        get 'htmlsrc'
        get 'preview'
      end
    end
    member do
      get 'getdata'
    end
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :campaigns do
    member do
      get 'getdata'
      get 'exception_form'
    end
  end

  resources :players, except: [:new, :create, :destroy] do
    member do
      post 'getdata'
      get 'getfiles'
      post 'sendCommand'
    end
  end

  resources :users

  resources :organizations, only: [:show, :edit, :update]

  get 'signup'  => 'users#new'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: :logout

  namespace :admin do
    root to: 'overview#index'
    resources :organizations, only: [:index, :show, :edit, :update, :new, :create, :destroy] do
      collection do
        post 'becomeOrg'
      end
    end
    resources :users, only: [:index, :edit, :update, :show, :new, :create, :destroy]
    resources :hardware_types
    resources :players do
      member do
        post 'resetconnection'
      end
    end
  end

end

app/views/shared/sidebar/_library_sidebar_items.html.erb
<li class="sidebar-header">Search</li>

<li class="sidebar-search">
    <div class="input-group custom-search-form">
        <input type="text" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
        <button class="btn btn-default" type="button">
            <i class="fa fa-search"></i>
        </button>
    </span>
    </div>
</li>

<li class="sidebar-header">Filter</li>

<li>
  <a href="javascript:void(0)" class="library-item" id="filter-images">
    <span class="flaticon-image84">Images</span>
    <span class="asset-count"><%= @image_assets_count %></span>
  </a>
</li>

<li>
  <a href="javascript:void(0)" class="library-item" id="filter-videos">
    <span class="flaticon-movie42">Movies</span>
    <span class="asset-count"><%= @video_assets_count %></span>
  </a>
</li>

<li class="sidebar-header">Sort</li>

<li>
  <a href="javascript:void(0)" class="library-item">
    <span class="flaticon-male40">Name</span>
    <input type="checkbox" data-toggle="toggle" data-size="mini">
  </a>
</li>

<li>
  <a href="javascript:void(0)" class="library-item">
    <span class="flaticon-male40">Size</span>
    <input type="checkbox" data-toggle="toggle" data-size="mini">
  </a>
</li>

<li>
  <a href="javascript:void(0)" class="library-item">
    <span class="flaticon-male40">Duration</span>
    <input type="checkbox" data-toggle="toggle" data-size="mini">
  </a>
</li>

<li>
  <a href="javascript:void(0)" class="library-item">
    <span class="flaticon-male40">Uploaded</span>
    <input type="checkbox" data-toggle="toggle" data-size="mini">
  </a>
</li>

app/views/shared/sidebar/_nav_header.html.erb
<% if current_page?  media_assets_path %>
  <!-- <li class="sidebar-upload-wrapper library">
    <a href="/media_assets/new">
      <i class="flaticon-cloud334"></i><p class="btn-text">Upload New</p>
    </a>
  </li> -->
  <li class="sidebar-upload-wrapper"></li>
<% elsif current_page? loop_assets_path %>
  <!-- <li class="sidebar-upload-wrapper loop">
    <a href="/loop_assets/new">
      <i class="flaticon-cloud334"></i><p class="btn-text">Create New</p>
    </a>
  </li> -->
  <li class="sidebar-upload-wrapper"></li>
<% elsif current_page? campaigns_path %>
  <li class="sidebar-upload-wrapper campaign text-center">
    <a href="/campaigns/new">
      <i class="flaticon-cloud334"></i><p class="btn-text">New Campaign</p>
    </a>
  </li>
<% else %>
  <li class="sidebar-upload-wrapper"></li>
<% end %>