config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :pay_programs
  end

  root 'overview#index'

  get 'overview' => 'overview#index', as: :overview

  put 'update_title' =>  'media_assets#update_title'

  resources :media_assets, path: 'library' do
    collection do
      get 'library'
      delete 'destroy_multiple'
    end
  end

  resources :template_addons

  resources :loop_assets do
    resources :slide_assets, except: [:index, :destroy] do
      member do
        get 'htmlsrc'
        get 'preview'
      end
    end
    member do
      get 'getdata'
    end
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :campaigns do
    member do
      get 'getdata'
      get 'exception_form'
    end
  end

  resources :players, except: [:new, :create, :destroy] do
    member do
      post 'getdata'
      get 'getfiles'
      post 'sendCommand'
    end
  end

  resources :users

  resources :organizations, only: [:show, :edit, :update]

  get 'signup'  => 'users#new'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: :logout

  namespace :admin do
    root to: 'overview#index'
    resources :organizations, only: [:index, :show, :edit, :update, :new, :create, :destroy] do
      collection do
        post 'becomeOrg'
      end
    end
    resources :users, only: [:index, :edit, :update, :show, :new, :create, :destroy]
    resources :hardware_types
    resources :players do
      member do
        post 'resetconnection'
      end
    end
  end

end

app/controllers/admin/hardware_types_controller.rb
class Admin::HardwareTypesController < ApplicationController
  include AuthenticateUser
  
  before_action :logged_in_user
  before_action :soadmin_user
  before_action :set_admin_hardware_type, only: [:show, :edit, :update, :destroy]

  # GET /admin/hardware_types
  # GET /admin/hardware_types.json
  def index
    @admin_hardware_types = Admin::HardwareType.all
  end

  # GET /admin/hardware_types/1
  # GET /admin/hardware_types/1.json
  def show
  end

  # GET /admin/hardware_types/new
  def new
    @admin_hardware_type = Admin::HardwareType.new
  end

  # GET /admin/hardware_types/1/edit
  def edit
  end

  # POST /admin/hardware_types
  # POST /admin/hardware_types.json
  def create
    @admin_hardware_type = Admin::HardwareType.new(admin_hardware_type_params)

    respond_to do |format|
      if @admin_hardware_type.save
        format.html { redirect_to @admin_hardware_type, notice: 'Hardware type was successfully created.' }
        format.json { render :show, status: :created, location: @admin_hardware_type }
      else
        format.html { render :new }
        format.json { render json: @admin_hardware_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/hardware_types/1
  # PATCH/PUT /admin/hardware_types/1.json
  def update
    respond_to do |format|
      if @admin_hardware_type.update(admin_hardware_type_params)
        format.html { redirect_to @admin_hardware_type, notice: 'Hardware type was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_hardware_type }
      else
        format.html { render :edit }
        format.json { render json: @admin_hardware_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/hardware_types/1
  # DELETE /admin/hardware_types/1.json
  def destroy
    @admin_hardware_type.destroy
    respond_to do |format|
      format.html { redirect_to admin_hardware_types_url, notice: 'Hardware type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_hardware_type
      @admin_hardware_type = Admin::HardwareType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_hardware_type_params
      params.require(:admin_hardware_type).permit(:model_number, :description)
    end
end

app/helpers/admin/hardware_types_helper.rb
module Admin::HardwareTypesHelper
end

app/views/admin/hardware_types/_form.html.erb
<%= form_for(@admin_hardware_type) do |f| %>
  <% if @admin_hardware_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_hardware_type.errors.count, "error") %> prohibited this admin_hardware_type from being saved:</h2>

      <ul>
      <% @admin_hardware_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model_number %><br>
    <%= f.text_field :model_number %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/hardware_types/edit.html.erb
<%= render partial: 'admin/shared/admin_nav' %>

<h1>Editing admin_hardware_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_hardware_type %> |
<%= link_to 'Back', admin_hardware_types_path %>

app/views/admin/hardware_types/index.html.erb
<%= render partial: 'admin/shared/admin_nav' %>

<h1>Listing admin_hardware_types</h1>

<table>
  <thead>
    <tr>
      <th>Model number</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_hardware_types.each do |admin_hardware_type| %>
      <tr>
        <td><%= admin_hardware_type.model_number %></td>
        <td><%= admin_hardware_type.description %></td>
        <td><%= link_to 'Show', admin_hardware_type %></td>
        <td><%= link_to 'Edit', edit_admin_hardware_type_path(admin_hardware_type) %></td>
        <td><%= link_to 'Destroy', admin_hardware_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hardware type', new_admin_hardware_type_path %>

app/views/admin/hardware_types/new.html.erb
<%= render partial: 'admin/shared/admin_nav' %>
<h1>New admin_hardware_type</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_hardware_types_path %>

app/views/admin/hardware_types/show.html.erb
<%= render partial: 'admin/shared/admin_nav' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Model number:</strong>
  <%= @admin_hardware_type.model_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_hardware_type.description %>
</p>

<%= link_to 'Edit', edit_admin_hardware_type_path(@admin_hardware_type) %> |
<%= link_to 'Back', admin_hardware_types_path %>