config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :pay_programs
  end

  root 'overview#index'

  get 'overview' => 'overview#index', as: :overview

  put 'update_title' =>  'media_assets#update_title'

  resources :media_assets, path: 'library' do
    collection do
      get 'library'
      delete 'destroy_multiple'
    end
  end

  resources :template_addons

  resources :loop_assets do
    resources :slide_assets, except: [:index, :destroy] do
      member do
        get 'htmlsrc'
        get 'preview'
      end
    end
    member do
      get 'getdata'
    end
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :campaigns do
    member do
      get 'getdata'
      get 'exception_form'
    end
  end

  resources :players, except: [:new, :create, :destroy] do
    member do
      post 'getdata'
      get 'getfiles'
      post 'sendCommand'
    end
  end

  resources :users

  resources :organizations, only: [:show, :edit, :update]

  get 'signup'  => 'users#new'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: :logout

  namespace :admin do
    root to: 'overview#index'
    resources :organizations, only: [:index, :show, :edit, :update, :new, :create, :destroy] do
      collection do
        post 'becomeOrg'
      end
    end
    resources :users, only: [:index, :edit, :update, :show, :new, :create, :destroy]
    resources :hardware_types
    resources :players do
      member do
        post 'resetconnection'
      end
    end
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
	has_many :users, inverse_of: :organization, dependent: :destroy
	has_many :players, inverse_of: :organization
	has_many :media_assets, inverse_of: :organization
	has_many :loop_assets, inverse_of: :organization
	has_many :slide_assets, inverse_of: :organization
	has_many :slide_templates, inverse_of: :organization
	has_many :slide_media_hooks, inverse_of: :organization
	has_many :campaigns, inverse_of: :organization
	has_many :user_logs, inverse_of: :organization
	
	validates :name, presence: true, length: { minimum: 3, maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
	validates :phone, length: { minimum: 10, maximum: 100 }
	validates :fname, presence: true, length: { maximum: 50 }
	validates :lname, presence: true, length: { maximum: 50 }
	validates :address1, presence: true, length: { maximum: 100 }
	validates :address2, length: { maximum: 100 }
	validates :address3, length: { maximum: 100 }
	validates :city, presence: true, length: { maximum: 255 }
	validates :province, presence: true, length: { maximum: 255 }
	validates :postalcode, presence: true, length: { maximum: 16 }
	validates :baddress1, presence: true, length: { maximum: 100 }
	validates :baddress2, length: { maximum: 100 }
	validates :baddress3, length: { maximum: 100 }
	validates :bcity, presence: true, length: { maximum: 255 }
	validates :bprovince, presence: true, length: { maximum: 255 }
	validates :bpostalcode, presence: true, length: { maximum: 16 }

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < ApplicationController
  include FlashMessages
  include AuthenticateUser

  before_action :logged_in_user
  before_action :soadmin_user
  before_action :set_organization, only: [:destroy, :show, :edit, :update]

  # GET /admin/organizations
  def index
    @organizations = Organization.all
  end

  # GET /admin/organizations/new
  def new
    @organization = Organization.new
  end

  # POST /admin/organizations
  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      redirect_to @organization, notice: 'Organization was successfully created.'
    else
      render :new
    end
  end

  # GET /admin/organizations/1
  def show
  end

  # GET /admin/organizations/1/edit
  def edit
  end

  # PATCH/PUT /admin/organizations/1
  def update
    if @organization.update(organization_params)
      redirect_to [:admin, @organization], notice: 'Organization was successfully updated.'
    else
      render :edit
    end
  end

    # DELETE /admin/organizations/1
  def destroy
    @organization.destroy
    redirect_to admin_organizations_url, notice: 'Organization was successfully destroyed.'
  end

  # POST /admin/organizations/becomeOrg
  def becomeOrg
    id = params[:orgid].to_i
    if !Organization.find_by_id(id)
      flash[:error] = "Org not found."
      redirect_to admin_root_url
    else
      current_user.organization = Organization.find(id)
      if current_user.save
        flash[:notice] = "You have been switched to organization '#{current_user.organization.name}'."
        redirect_to admin_root_url
      else
        flash[:error] = "Error saving new organization id"
        redirect_to admin_root_url
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :email, :phone, :fname, :lname, :address1, :address2, :address3, :city, :province, :postalcode, :baddress1, :baddress2, :baddress3, :bcity, :bprovince, :bpostalcode)
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  include FlashMessages
  include AuthenticateUser

  before_action :logged_in_user
  before_action :orgadmin_user, only: [:edit, :update]
  before_action :set_organization, only: [:show, :edit, :update]

  # GET /organizations/1
  def show
  end

  # GET /organizations/1/edit
  def edit
  end

  # PATCH/PUT /organizations/1
  def update
    if @organization.update(organization_params)
      redirect_to @organization, notice: 'Organization was successfully updated.'
    else
      render :edit
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
      if !current_user.soadmin && current_user.organization != @organization
        redirect_to current_user.organization
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :email, :phone, :fname, :lname, :address1, :address2, :address3, :city, :province, :postalcode, :baddress1, :baddress2, :baddress3, :bcity, :bprovince, :bpostalcode)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/admin/organizations/_form.html.erb
<%= form_for([:admin, @organization]) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Organization Name' %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email, 'Contact Email' %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone, 'Contact Phone Number' %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :fname, 'Contact First Name' %>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname, 'Contact Last Name' %>
    <%= f.text_field :lname %>
  </div>
  <h3>Shipping Address:</h3>
  <div class="field">
    <%= f.label :address1, 'Address Line 1' %>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2, 'Address Line 2' %>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :address3, 'Address Line 3' %>
    <%= f.text_field :address3 %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :province, 'Province/State' %>
    <%= f.text_field :province %>
  </div>
  <div class="field">
    <%= f.label :postalcode, 'Postal/Zip Code' %>
    <%= f.text_field :postalcode %>
  </div>
  <h3>Billing Address:</h3>
  <div class="field">
    <%= f.label :baddress1, 'Billing Address Line 1'%>
    <%= f.text_field :baddress1 %>
  </div>
  <div class="field">
    <%= f.label :baddress2, 'Billing Address  Line 2' %>
    <%= f.text_field :baddress2 %>
  </div>
  <div class="field">
    <%= f.label :baddress3, 'Billing Address Line 3' %>
    <%= f.text_field :baddress3 %>
  </div>
  <div class="field">
    <%= f.label :bcity, 'City' %>
    <%= f.text_field :bcity %>
  </div>
  <div class="field">
    <%= f.label :bprovince, 'Province/State' %>
    <%= f.text_field :bprovince %>
  </div>
  <div class="field">
    <%= f.label :bpostalcode, 'Postal/Zip Code'%>
    <%= f.text_field :bpostalcode %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/organizations/edit.html.erb
<%= render partial: 'admin/shared/admin_nav' %>
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @organization] %>

app/views/admin/organizations/index.html.erb
<%= render partial: 'admin/shared/admin_nav' %>
<h1>Listing organizations</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.email %></td>
        <td><%= organization.phone %></td>
        <td><%= link_to 'Show', [:admin, organization] %></td>
        <td><%= link_to 'Edit', edit_admin_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', [:admin, organization], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= button_to 'JOIN', becomeOrg_admin_organizations_path, {:params => {orgid: organization.id}} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_admin_organization_path %>

app/views/admin/organizations/new.html.erb
<%= render partial: 'admin/shared/admin_nav' %>
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_organizations_path %>

app/views/admin/organizations/show.html.erb
<%= render partial: 'admin/shared/admin_nav' %>
<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @organization.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @organization.phone %>
</p>

<p>
  <strong>Contact Fist Name:</strong>
  <%= @organization.fname %>
</p>

<p>
  <strong>Contact Last Name:</strong>
  <%= @organization.lname %>
</p>

<h3>Shipping Address:</h3>
<p>
  <strong>Address Line 1:</strong>
  <%= @organization.address1 %>
</p>

<p>
  <strong>Address Line 2:</strong>
  <%= @organization.address2 %>
</p>

<p>
  <strong>Address Line 3:</strong>
  <%= @organization.address3 %>
</p>

<p>
  <strong>City:</strong>
  <%= @organization.city %>
</p>

<p>
  <strong>Province/State:</strong>
  <%= @organization.province %>
</p>

<p>
  <strong>Postal/Zip Code:</strong>
  <%= @organization.postalcode %>
</p>

<h3>Billing Address:</h3>
<p>
  <strong>Address Line 1:</strong>
  <%= @organization.baddress1 %>
</p>

<p>
  <strong>Address Line 2:</strong>
  <%= @organization.baddress2 %>
</p>

<p>
  <strong>Address Line 3:</strong>
  <%= @organization.baddress3 %>
</p>

<p>
  <strong>City:</strong>
  <%= @organization.bcity %>
</p>

<p>
  <strong>Province/State</strong>
  <%= @organization.bprovince %>
</p>

<p>
  <strong>Postal/Zip Code:</strong>
  <%= @organization.bpostalcode %>
</p>


<p><%= link_to 'Add User', new_admin_user_path(:orgid => @organization.id) %></p>
<p><%= link_to 'Add Player', new_admin_player_path(:orgid => @organization.id) %></p>